DefaultContentLanguage = "en"
baseURL = "https://agucova.dev/"
languageCode = "en-us"
languageName = "English"
title = "AgustÃ­n Covarrubias"

canonifyURLs = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[params]
author = "AgustÃ­n Covarrubias"
description = "ğŸ‘¨â€ğŸ’» A student and open sourcerer that does a bit of everything, none specially well."
headline = "Student and open sourcerer"
sitename = "AgustÃ­n Covarrubias"

github = "agucova"
keybase = "agucova"
linkedin = "agucova"
twitter = "austinc3301"

dateFormat = "Jan 2, 2021"

homeTitle = "Hi there, I'm Agus ğŸ‘‹"
homeBody = """
> "Somewhere, something incredible is waiting to be known."
> â€” Carl Sagan

I'm an engineering student and [open sourcerer](https://github.com/agucova) that does a bit of everything, nothing specially well. I'm from Chile  ğŸ‡¨ğŸ‡± and I'm currently an undergraduate majoring in Computer Science Engineering ğŸ‘¨â€ğŸ’» at [UC Chile](https://www.uc.cl/en).

I'm very passionate about computer science, cybersecurity and using tech for social impact. I do a lot of interdisciplinary work, spanning everything from edtech to metascience, and I've also been involved in public policy, campaigning and consultancy.

I'm the Digital Platforms Lead at [AmÃ©rica Transparente](https://americatransparente.org/), an NGO working on enabling government transparency throughout Latin America by building open source tools for journalists. I've also been an organizer of [March for Science](https://marchforscience.org/) Chile since 2017, working to push for better scientific policy in Chile.

I co-founded the [Assembly for Knowledge and Research](https://acic.cl) and [Open Source UC](https://osuc.dev/).

ğŸ’¬ Feel free to contact me if you're looking to collaborate on something!

My pronouns are he/him.
"""


[languages]
[language.en]
languageCode = "en-us"
languageName = "English"
weight = 1

[language.es]
languageCode = "es"
languageName = "Spanish"
weight = 2

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
