DefaultContentLanguage = "en"
baseURL = "https://agucova.dev/"
languageCode = "en-us"
languageName = "English"
title = "AgustÃ­n Covarrubias"

canonifyURLs = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[params]
author = "AgustÃ­n Covarrubias"
description = "ðŸ‘¨â€ðŸ’» A student and open sourcerer that does a bit of everything, none specially well."
headline = "Student and open sourcerer"
sitename = "AgustÃ­n Covarrubias"

github = "agucova"
keybase = "agucova"
linkedin = "agucova"
twitter = "austinc3301"

dateFormat = "Jan 2, 2021"
homeBody = """
> "Somewhere, something incredible is waiting to be known."
> â€” Carl Sagan

I'm a student and open sourcerer that does a bit of everything, none specially well. I'm from Chile (ðŸ‡¨ðŸ‡±) and I'm currently studying engineering at the Universidad CatÃ³lica de Chile.

I program in C and Python but I'm constantly learning and toying with new languages, currently Nim. My main interest is biomedical engineering, but I'm also interested in Computer Science (go CS50x!), Quantified Self and Meta-Science, along with a bunch of other things. I'm a yearly organizer of March for Science Chile.

ðŸ’¬ Feel free to contact me if you're looking to collaborate on something!

My pronouns are he/him.
"""
homeTitle = "Hi there, I'm AgustÃ­n ðŸ‘‹"
[languages]
[language.en]
languageCode = "en-us"
languageName = "English"
weight = 1

[language.es]
languageCode = "es"
languageName = "Spanish"
weight = 2
