DefaultContentLanguage = "en"
baseURL = "https://agucova.dev/"
languageCode = "en-us"
languageName = "English"
title = "AgustÃ­n Covarrubias"

canonifyURLs = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[params]
author = "AgustÃ­n Covarrubias"
description = "ğŸ‘¨â€ğŸ’» A student and open sourcerer that does a bit of everything, none specially well."
headline = "Student and open sourcerer"
sitename = "AgustÃ­n Covarrubias"

github = "agucova"
keybase = "agucova"
linkedin = "agucova"
twitter = "austinc3301"

dateFormat = "Jan 2, 2021"
homeBody = """
> "Somewhere, something incredible is waiting to be known."
> â€” Carl Sagan

I'm an engineering student and [open sourcerer](https://github.com/agucova) that does a bit of everything, none specially well. I'm from Chile  ğŸ‡¨ğŸ‡± and I'm currently majoring in Computing Engineering ğŸ‘¨â€ğŸ’» at [UC Chile](https://www.uc.cl/en).

I program mostly in Python and Julia, but I'm constantly learning and toying with new languages, currently Rust. I'm strongly interested in interdisciplinary scientific work, spanning everything from biomedical engineering to [metascience](https://en.wikipedia.org/wiki/Metascience). 

I've been an organizer of March for Science Chile since 2017, and I currently volunteer as a back-end and infrastructure engineer at [AmÃ©rica Transparente](https://americatransparente.org/), an NGO working on enabling government transparency throughout Latin America.

ğŸ’¬ Feel free to contact me if you're looking to collaborate on something!

My pronouns are he/him.
"""
homeTitle = "Hi there, I'm AgustÃ­n ğŸ‘‹"
[languages]
[language.en]
languageCode = "en-us"
languageName = "English"
weight = 1

[language.es]
languageCode = "es"
languageName = "Spanish"
weight = 2
